name: Pablic Enemy
favicon: null
layout_spectrum: 0.981746684294194
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#fefefe'
    - '#6b5238'
    - '#a89a7d'
    - '#54888f'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
